export default {
  DOCKER: 'DOCKER',
  STATIC: 'STATIC',
  SPRING_BOOT: 'SPRING_BOOT',
  VUE: 'VUE',
  LARAVEL: 'LARAVEL',
  DJANGO: 'DJANGO',
  ANGULAR: 'ANGULAR',
  REACT: 'REACT',
  RUBY_ON_RAILS: 'RUBY_ON_RAILS',
  EXPRESS: 'EXPRESS',
  DOT_NET: 'DOT_NET',
  NIXPACKS: 'NIXPACKS',
  NEXT: 'NEXT',
  NUXT: 'NUXT'
}




